# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  database: fastermen_development
  pool: 25
production:
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  database: fastermen_development
  pool: 25
