# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ab031358077b946878dbbe3981c8b861cfe859b52a73e34a981759240619f5f63435c1e8d7cd769e747851faeaf988ee3542bfe049963c65b2c02d480789473

test:
  secret_key_base: c79e36f66946182f83c68e3a1d5b7840f08eedb44f314d4ab366ab35311c51bf5fc3a417dc507d36396b8fbb88dcac828872d4cca648c676ad3487ed4de97b47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
